### ISSUE TITLE
Mudar a sede da Associação para SP

### ISSUE THREAD

**Issue by osantana** [pythonbrasil/estatuto#1]

**Comment by taniaa** [comment]
Verificamos que não vale a pena mudar a sede. A contadora nos atende bem, mesmo com o aumento de demanda dos últimos anos e temos resolvido as burocracias financeiras com outros recursos (como token). 

Esta issue se relacionava com esta outra, já fechada: https://github.com/pythonbrasil/apyb.gerenciamento/issues/12
