### ISSUE TITLE
Diminuir os cargos de Diretoria

### ISSUE THREAD

**Issue by osantana** [pythonbrasil/estatuto#5]
Presidência
Vice-Presidencia
Financeiro
Marketing
Operacional (antigo Online)

**Comment by leorochael** [comment]
Concluído no PR #11, resultado [da assembleia em 2013-10-02](https://github.com/pythonbrasil/estatuto/blob/1c2720d93da5b22a869c5e8923db99a193217ad9/assembleia-2013/ata-008-draft.md).
